### ISSUE TITLE
It crashes again

### ISSUE THREAD

**Issue by redyolocraft** [Aerion/uptobox-dl#11]
Hi, I downloaded the new version. I start downloading 3 folders. It downloads the first one and then crashes. I relaunch it and it crashes again.

The complete logs with the links are in the email inbox [biwessautaugra-5025@yopmail.com](mailto:biwessautaugra-5025@yopmail.com). Please delete the email. Did I do something wrong?

uptobox-dl -t REDACTED "https://uptobox.com/user_public?hash=REDACTED&folder=REDACTED" "https://uptobox.com/user_public?hash=REDACTED&folder=REDACTED" "https://uptobox.com/user_public?hash=REDACTED&folder=REDACTED"

Caught exception - retrying once: System.InvalidOperationException: The requested operation requires an element of type 'String', but the target element has type 'Object'.
   at System.Text.Json.JsonDocument.CheckExpectedType(JsonTokenType , JsonTokenType )
   at System.Text.Json.JsonDocument.GetString(Int32 , JsonTokenType )
   at System.Text.Json.JsonElement.GetString()
   at UptoboxDl.UptoboxClient.Client.DeserializeJsonElementFromStream(Stream stream) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 124
   at UptoboxDl.UptoboxClient.Client.GetAsync(Uri uri, CancellationToken ct) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 106
   at UptoboxDl.UptoboxClient.Client.GetAsync[T](Uri uri, CancellationToken ct) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 111
   at UptoboxDl.UptoboxClient.Client.GetWaitingTokenAsync(String fileCode, String password, CancellationToken cancellationToken) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 56
   at UptoboxDl.Program.RetryOnFailure[T](Func`1 task) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 171
Caught exception - retrying once: System.InvalidOperationException: The requested operation requires an element of type 'String', but the target element has type 'Object'.
   at System.Text.Json.JsonDocument.CheckExpectedType(JsonTokenType , JsonTokenType )
   at System.Text.Json.JsonDocument.GetString(Int32 , JsonTokenType )
   at System.Text.Json.JsonElement.GetString()
   at UptoboxDl.UptoboxClient.Client.DeserializeJsonElementFromStream(Stream stream) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 124
   at UptoboxDl.UptoboxClient.Client.GetAsync(Uri uri, CancellationToken ct) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 106
   at UptoboxDl.UptoboxClient.Client.GetAsync[T](Uri uri, CancellationToken ct) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 111
   at UptoboxDl.UptoboxClient.Client.GetWaitingTokenAsync(String fileCode, String password, CancellationToken cancellationToken) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 56
   at UptoboxDl.Program.RetryOnFailure[T](Func`1 task) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 178
   at UptoboxDl.Program.GetValidWaitingTokenAsync(String fileCode) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 147
   at UptoboxDl.Program.ProcessLink(String fileCode, Options opts) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 130
   at UptoboxDl.Program.RetryOnFailure(Func`1 task) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 186

Caught exception - retrying once: System.InvalidOperationException: The requested operation requires an element of type 'String', but the target element has type 'Object'.
   at System.Text.Json.JsonDocument.CheckExpectedType(JsonTokenType , JsonTokenType )
   at System.Text.Json.JsonDocument.GetString(Int32 , JsonTokenType )
   at System.Text.Json.JsonElement.GetString()
   at UptoboxDl.UptoboxClient.Client.DeserializeJsonElementFromStream(Stream stream) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 124
   at UptoboxDl.UptoboxClient.Client.GetAsync(Uri uri, CancellationToken ct) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 106
   at UptoboxDl.UptoboxClient.Client.GetAsync[T](Uri uri, CancellationToken ct) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 111
   at UptoboxDl.UptoboxClient.Client.GetWaitingTokenAsync(String fileCode, String password, CancellationToken cancellationToken) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 56
   at UptoboxDl.Program.RetryOnFailure[T](Func`1 task) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 171
Unhandled exception. System.InvalidOperationException: The requested operation requires an element of type 'String', but the target element has type 'Object'.
   at System.Text.Json.JsonDocument.CheckExpectedType(JsonTokenType , JsonTokenType )
   at System.Text.Json.JsonDocument.GetString(Int32 , JsonTokenType )
   at System.Text.Json.JsonElement.GetString()
   at UptoboxDl.UptoboxClient.Client.DeserializeJsonElementFromStream(Stream stream) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 124
   at UptoboxDl.UptoboxClient.Client.GetAsync(Uri uri, CancellationToken ct) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 106
   at UptoboxDl.UptoboxClient.Client.GetAsync[T](Uri uri, CancellationToken ct) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 111
   at UptoboxDl.UptoboxClient.Client.GetWaitingTokenAsync(String fileCode, String password, CancellationToken cancellationToken) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 56
   at UptoboxDl.Program.RetryOnFailure[T](Func`1 task) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 178
   at UptoboxDl.Program.GetValidWaitingTokenAsync(String fileCode) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 147
   at UptoboxDl.Program.ProcessLink(String fileCode, Options opts) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 130
   at UptoboxDl.Program.RetryOnFailure(Func`1 task) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 194
   at UptoboxDl.Program.Main(String[] args) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 67
   at UptoboxDl.Program.<Main>(String[] args)

Caught exception - retrying once: System.InvalidOperationException: The requested operation requires an element of type 'String', but the target element has type 'Object'.
   at System.Text.Json.JsonDocument.CheckExpectedType(JsonTokenType , JsonTokenType )
   at System.Text.Json.JsonDocument.GetString(Int32 , JsonTokenType )
   at System.Text.Json.JsonElement.GetString()
   at UptoboxDl.UptoboxClient.Client.DeserializeJsonElementFromStream(Stream stream) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 124
   at UptoboxDl.UptoboxClient.Client.GetAsync(Uri uri, CancellationToken ct) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 106
   at UptoboxDl.UptoboxClient.Client.GetAsync[T](Uri uri, CancellationToken ct) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 111
   at UptoboxDl.UptoboxClient.Client.GetWaitingTokenAsync(String fileCode, String password, CancellationToken cancellationToken) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 56
   at UptoboxDl.Program.RetryOnFailure[T](Func`1 task) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 171
Caught exception - retrying once: System.InvalidOperationException: The requested operation requires an element of type 'String', but the target element has type 'Object'.
   at System.Text.Json.JsonDocument.CheckExpectedType(JsonTokenType , JsonTokenType )
   at System.Text.Json.JsonDocument.GetString(Int32 , JsonTokenType )
   at System.Text.Json.JsonElement.GetString()
   at UptoboxDl.UptoboxClient.Client.DeserializeJsonElementFromStream(Stream stream) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 124
   at UptoboxDl.UptoboxClient.Client.GetAsync(Uri uri, CancellationToken ct) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 106
   at UptoboxDl.UptoboxClient.Client.GetAsync[T](Uri uri, CancellationToken ct) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 111
   at UptoboxDl.UptoboxClient.Client.GetWaitingTokenAsync(String fileCode, String password, CancellationToken cancellationToken) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 56
   at UptoboxDl.Program.RetryOnFailure[T](Func`1 task) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 178
   at UptoboxDl.Program.GetValidWaitingTokenAsync(String fileCode) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 147
   at UptoboxDl.Program.ProcessLink(String fileCode, Options opts) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 130
   at UptoboxDl.Program.RetryOnFailure(Func`1 task) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 186

Caught exception - retrying once: System.InvalidOperationException: The requested operation requires an element of type 'String', but the target element has type 'Object'.
   at System.Text.Json.JsonDocument.CheckExpectedType(JsonTokenType , JsonTokenType )
   at System.Text.Json.JsonDocument.GetString(Int32 , JsonTokenType )
   at System.Text.Json.JsonElement.GetString()
   at UptoboxDl.UptoboxClient.Client.DeserializeJsonElementFromStream(Stream stream) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 124
   at UptoboxDl.UptoboxClient.Client.GetAsync(Uri uri, CancellationToken ct) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 106
   at UptoboxDl.UptoboxClient.Client.GetAsync[T](Uri uri, CancellationToken ct) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 111
   at UptoboxDl.UptoboxClient.Client.GetWaitingTokenAsync(String fileCode, String password, CancellationToken cancellationToken) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 56
   at UptoboxDl.Program.RetryOnFailure[T](Func`1 task) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 171
Unhandled exception. System.InvalidOperationException: The requested operation requires an element of type 'String', but the target element has type 'Object'.
   at System.Text.Json.JsonDocument.CheckExpectedType(JsonTokenType , JsonTokenType )
   at System.Text.Json.JsonDocument.GetString(Int32 , JsonTokenType )
   at System.Text.Json.JsonElement.GetString()
   at UptoboxDl.UptoboxClient.Client.DeserializeJsonElementFromStream(Stream stream) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 124
   at UptoboxDl.UptoboxClient.Client.GetAsync(Uri uri, CancellationToken ct) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 106
   at UptoboxDl.UptoboxClient.Client.GetAsync[T](Uri uri, CancellationToken ct) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 111
   at UptoboxDl.UptoboxClient.Client.GetWaitingTokenAsync(String fileCode, String password, CancellationToken cancellationToken) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 56
   at UptoboxDl.Program.RetryOnFailure[T](Func`1 task) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 178
   at UptoboxDl.Program.GetValidWaitingTokenAsync(String fileCode) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 147
   at UptoboxDl.Program.ProcessLink(String fileCode, Options opts) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 130
   at UptoboxDl.Program.RetryOnFailure(Func`1 task) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 194
   at UptoboxDl.Program.Main(String[] args) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 67

**Comment by Aerion** [comment]
I tested the latest version too quickly, this new one [v1.4.1](https://github.com/Aerion/uptobox-dl/releases/tag/v1.4.1) should fix it.
Thanks for the report :+1:
