### ISSUE TITLE
Issue while downloading from UptoBox

### ISSUE THREAD

**Issue by shivaram1231231** [Aerion/uptobox-dl#12]
I am getting the following error when I try to download using uptobox-dl.exe. I entered my Uptobox token and the file from uptobox.

CMD: uptobox-dl.exe -t <my_user_token> https://uptobox.com/<filecode_1>

Error:
1 files to download (from 1 direct links and 0 folders)
Start processing 1cnq13gnlj0y
Caught exception - retrying once: System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at UptoboxDl.Program.<>c.<DownloadFile>b__9_0(Object _, HttpProgressEventArgs args) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 206
   at System.Net.Http.Handlers.ProgressMessageHandler.OnHttpResponseProgress(HttpRequestMessage request, HttpProgressEventArgs e)
   at System.Net.Http.Handlers.ProgressStream.ReportBytesReceived(Int32 bytesReceived, Object userState)
   at System.Net.Http.Handlers.ProgressStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.<CopyToAsync>g__Core|29_0(Stream , Stream , Int32 , CancellationToken )
   at UptoboxDl.Program.DownloadFile(Uri link, String filename) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 220
   at UptoboxDl.Program.RetryOnFailure(Func`1 task) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 186
Caught exception - retrying once: System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at UptoboxDl.Program.<>c.<DownloadFile>b__9_0(Object _, HttpProgressEventArgs args) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 206
   at System.Net.Http.Handlers.ProgressMessageHandler.OnHttpResponseProgress(HttpRequestMessage request, HttpProgressEventArgs e)
   at System.Net.Http.Handlers.ProgressStream.ReportBytesReceived(Int32 bytesReceived, Object userState)
   at System.Net.Http.Handlers.ProgressStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.<CopyToAsync>g__Core|29_0(Stream , Stream , Int32 , CancellationToken )
   at UptoboxDl.Program.DownloadFile(Uri link, String filename) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 220
   at UptoboxDl.Program.RetryOnFailure(Func`1 task) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 194
   at UptoboxDl.Program.ProcessLink(String fileCode, Options opts) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 139
   at UptoboxDl.Program.RetryOnFailure(Func`1 task) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 186
Start processing 1cnq13gnlj0y
File Armour.of.God.II.Operation.Condor.1991.Extended.Cut.720p.BluRay.x264.950MB-[Mkvking.com].mkv already exists, will be overwritten as size are different: local 0 b, uptobox 950.86 MiB
Caught exception - retrying once: System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at UptoboxDl.Program.<>c.<DownloadFile>b__9_0(Object _, HttpProgressEventArgs args) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 206
   at System.Net.Http.Handlers.ProgressMessageHandler.OnHttpResponseProgress(HttpRequestMessage request, HttpProgressEventArgs e)
   at System.Net.Http.Handlers.ProgressStream.ReportBytesReceived(Int32 bytesReceived, Object userState)
   at System.Net.Http.Handlers.ProgressStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.<CopyToAsync>g__Core|29_0(Stream , Stream , Int32 , CancellationToken )
   at UptoboxDl.Program.DownloadFile(Uri link, String filename) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 220
   at UptoboxDl.Program.RetryOnFailure(Func`1 task) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 186
Unhandled exception. System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at UptoboxDl.Program.<>c.<DownloadFile>b__9_0(Object _, HttpProgressEventArgs args) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 206
   at System.Net.Http.Handlers.ProgressMessageHandler.OnHttpResponseProgress(HttpRequestMessage request, HttpProgressEventArgs e)
   at System.Net.Http.Handlers.ProgressStream.ReportBytesReceived(Int32 bytesReceived, Object userState)
   at System.Net.Http.Handlers.ProgressStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.<CopyToAsync>g__Core|29_0(Stream , Stream , Int32 , CancellationToken )
   at UptoboxDl.Program.DownloadFile(Uri link, String filename) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 220
   at UptoboxDl.Program.RetryOnFailure(Func`1 task) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 194
   at UptoboxDl.Program.ProcessLink(String fileCode, Options opts) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 139
   at UptoboxDl.Program.RetryOnFailure(Func`1 task) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 194
   at UptoboxDl.Program.Main(String[] args) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 67
   at UptoboxDl.Program.<Main>(String[] args)

G:\New folder\uptobox-dl-v1.4.1-win-x64>

Please advise.

**Comment by Aerion** [comment]
Hi, thanks for the report!
Could you please try out the new version [v1.4.2](https://github.com/Aerion/uptobox-dl/releases/tag/v1.4.2) that should address this specific issue?
Cheers
