### ISSUE TITLE
Caught exception - retrying once: UptoboxDl.UptoboxClient.ClientException: Error: Invalid_Parameter

### ISSUE THREAD

**Issue by venhow** [Aerion/uptobox-dl#14]
Caught exception - retrying once: UptoboxDl.UptoboxClient.ClientException: Error: Invalid_Parameter
   at UptoboxDl.UptoboxClient.Client.DeserializeJsonElementFromStream(Stream stream) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 125
   at UptoboxDl.UptoboxClient.Client.GetAsync(Uri uri, CancellationToken ct) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 105
   at UptoboxDl.UptoboxClient.Client.GetAsync[T](Uri uri, CancellationToken ct) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 110
   at UptoboxDl.UptoboxClient.Client.GetWaitingTokenAsync(String fileCode, String password, CancellationToken cancellationToken) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 55
   at UptoboxDl.Program.RetryOnFailure[T](Func`1 task) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 171
Caught exception - retrying once: UptoboxDl.UptoboxClient.ClientException: Error: Invalid_Parameter
   at UptoboxDl.UptoboxClient.Client.DeserializeJsonElementFromStream(Stream stream) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 125
   at UptoboxDl.UptoboxClient.Client.GetAsync(Uri uri, CancellationToken ct) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 105
   at UptoboxDl.UptoboxClient.Client.GetAsync[T](Uri uri, CancellationToken ct) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 110
   at UptoboxDl.UptoboxClient.Client.GetWaitingTokenAsync(String fileCode, String password, CancellationToken cancellationToken) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 55
   at UptoboxDl.Program.RetryOnFailure[T](Func`1 task) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 178
   at UptoboxDl.Program.GetValidWaitingTokenAsync(String fileCode) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 147
   at UptoboxDl.Program.ProcessLink(String fileCode, Options opts) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 130
   at UptoboxDl.Program.RetryOnFailure(Func`1 task) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 186

**Comment by venhow** [comment]
fixed: must using correct command format...
