### ISSUE TITLE
428 (Precondition Required) - System.Net.Http.HttpRequestException: Response status code does not indicate success

### ISSUE THREAD

**Issue by TheBoomerDev** [Aerion/uptobox-dl#15]
This error on Windows 11; version: 1.4.2

Caught exception - retrying once: System.Net.Http.HttpRequestException: Response status code does not indicate success: 428 (Precondition Required).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage , CancellationToken )
   at UptoboxDl.Program.DownloadFile(Uri link, String filename) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 228
   at UptoboxDl.Program.RetryOnFailure(Func`1 task) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 186

**Comment by benjamin-brl** [comment]
Uptobox refuse the connection for me 😢
```
Caught exception - retrying once: System.Net.Http.HttpRequestException: Aucune connexion n'a pu être établie car l'ordinateur cible l'a expressément refusée. (uptobox.com:443)
 ---> System.Net.Sockets.SocketException (10061): Aucune connexion n'a pu être établie car l'ordinateur cible l'a expressément refusée.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError , CancellationToken )
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 )
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs , ValueTask , CancellationToken )
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String , Int32 , HttpRequestMessage , Boolean , CancellationToken )
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String , Int32 , HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage )
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken )
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage , Boolean , Boolean , CancellationToken )
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage , HttpCompletionOption , CancellationTokenSource , Boolean , CancellationTokenSource , CancellationToken )
   at UptoboxDl.UptoboxClient.Client.GetAsync(Uri uri, CancellationToken ct) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 102
   at UptoboxDl.UptoboxClient.Client.GetAsync[T](Uri uri, CancellationToken ct) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 110
   at UptoboxDl.UptoboxClient.Client.GetFileCodeInfoAsync(String fileCode) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 95
   at UptoboxDl.Program.RetryOnFailure[T](Func`1 task) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 171
Unhandled exception. System.Net.Http.HttpRequestException: Aucune connexion n'a pu être établie car l'ordinateur cible l'a expressément refusée. (uptobox.com:443)
 ---> System.Net.Sockets.SocketException (10061): Aucune connexion n'a pu être établie car l'ordinateur cible l'a expressément refusée.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError , CancellationToken )
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 )
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs , ValueTask , CancellationToken )
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String , Int32 , HttpRequestMessage , Boolean , CancellationToken )
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String , Int32 , HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage )
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken )
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage , Boolean , Boolean , CancellationToken )
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage , HttpCompletionOption , CancellationTokenSource , Boolean , CancellationTokenSource , CancellationToken )
   at UptoboxDl.UptoboxClient.Client.GetAsync(Uri uri, CancellationToken ct) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 102
   at UptoboxDl.UptoboxClient.Client.GetAsync[T](Uri uri, CancellationToken ct) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 110
   at UptoboxDl.UptoboxClient.Client.GetFileCodeInfoAsync(String fileCode) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 95
   at UptoboxDl.Program.RetryOnFailure[T](Func`1 task) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 178
   at UptoboxDl.Program.ProcessLink(String fileCode, Options opts) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 106
   at UptoboxDl.Program.RetryOnFailure(Func`1 task) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 194
   at UptoboxDl.Program.Main(String[] args) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 67
   at UptoboxDl.Program.<Main>(String[] args)
https://uptobox.com/ttmpw2buqp8s
1 files to download (from 1 direct links and 0 folders)
Start processing ttmpw2buqp8s
Caught exception - retrying once: System.Net.Http.HttpRequestException: Aucune connexion n'a pu être établie car l'ordinateur cible l'a expressément refusée. (uptobox.com:443)
 ---> System.Net.Sockets.SocketException (10061): Aucune connexion n'a pu être établie car l'ordinateur cible l'a expressément refusée.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError , CancellationToken )
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 )
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs , ValueTask , CancellationToken )
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String , Int32 , HttpRequestMessage , Boolean , CancellationToken )
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String , Int32 , HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage )
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken )
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage , Boolean , Boolean , CancellationToken )
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage , HttpCompletionOption , CancellationTokenSource , Boolean , CancellationTokenSource , CancellationToken )
   at UptoboxDl.UptoboxClient.Client.GetAsync(Uri uri, CancellationToken ct) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 102
   at UptoboxDl.UptoboxClient.Client.GetAsync[T](Uri uri, CancellationToken ct) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 110
   at UptoboxDl.UptoboxClient.Client.GetFileCodeInfoAsync(String fileCode) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 95
   at UptoboxDl.Program.RetryOnFailure[T](Func`1 task) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 171
Caught exception - retrying once: System.Net.Http.HttpRequestException: Aucune connexion n'a pu être établie car l'ordinateur cible l'a expressément refusée. (uptobox.com:443)
 ---> System.Net.Sockets.SocketException (10061): Aucune connexion n'a pu être établie car l'ordinateur cible l'a expressément refusée.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError , CancellationToken )
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 )
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs , ValueTask , CancellationToken )
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String , Int32 , HttpRequestMessage , Boolean , CancellationToken )
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String , Int32 , HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage )
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken )
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage , Boolean , Boolean , CancellationToken )
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage , HttpCompletionOption , CancellationTokenSource , Boolean , CancellationTokenSource , CancellationToken )
   at UptoboxDl.UptoboxClient.Client.GetAsync(Uri uri, CancellationToken ct) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 102
   at UptoboxDl.UptoboxClient.Client.GetAsync[T](Uri uri, CancellationToken ct) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 110
   at UptoboxDl.UptoboxClient.Client.GetFileCodeInfoAsync(String fileCode) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\UptoboxClient\Client.cs:line 95
   at UptoboxDl.Program.RetryOnFailure[T](Func`1 task) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 178
   at UptoboxDl.Program.ProcessLink(String fileCode, Options opts) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 106
   at UptoboxDl.Program.RetryOnFailure(Func`1 task) in D:\a\uptobox-dl\uptobox-dl\uptobox-dl\Program.cs:line 186
```
